### ISSUE TITLE
Example in readme gives TypeError

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#123]
The current example in README.rst:

```python
from symfit import parameters, variables, Fit, Model

xdata = [1.0, 2.0, 3.0, 4.0, 5.0]
ydata = [2.3, 3.3, 4.1, 5.5, 6.7]
yerr = [0.1, 0.1, 0.1, 0.1, 0.1]

a, b = parameters('a, b')
x, y = variables('x, y')
model = Model({y: a * x + b})

fit = Fit(model, x=xdata, y=ydata, sigma_y=yerr)
fit_result = fit.execute()
```

```
TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'
```

Fixed by inputting np.npdarrays instead of listst
```python
from symfit import parameters, variables, Fit, Model
import numpy as np

xdata = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
ydata = np.array([2.3, 3.3, 4.1, 5.5, 6.7])
yerr = np.array([0.1, 0.1, 0.1, 0.1, 0.1])

a, b = parameters('a, b')
x, y = variables('x, y')
model = Model({y: a * x + b})

fit = Fit(model, x=xdata, y=ydata, sigma_y=yerr)
fit_result = fit.execute()
```

A type check or conversion to `np.ndarray` would be nice. 

Also this example shows yet another way of defining models, IMO this adds to confusion.

**Comment by tBuLi** [comment]
You are right, this should work.

The reason I did not do this before is because I didn't want to force people to use numpy, and to leave duck-typing intact. But by now numpy is implicitely assumed anyway so I will fix this.

To my knowledge though, this is only one of two ways to define models in the docs right? Either by a dict, or directly. Personally I think this way is the clearest, as it allows for named assignment of the data in `Fit`.
