### ISSUE TITLE
Order of Operations

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#124]
Lets say I'd have a bunch of datasets and I want to fit them all. Actually, I do have a bunch of datasets which I want to fit all, but for now lets generate some data:

```python
from __future__ import print_function
from symfit import Parameter, Variable, Fit, exp
import numpy as np

sample = np.random.normal(loc=15.0, scale=1.5, size=(10000,))
ydata1, bin_edges = np.histogram(sample, 100)
xdata1 = (bin_edges[1:] + bin_edges[:-1])/2

sample = np.random.normal(loc=500.0, scale=50, size=(10000,))
ydata2, bin_edges = np.histogram(sample, 100)
xdata2 = (bin_edges[1:] + bin_edges[:-1])/2


def model_maker(x0=15, sig=50):
    x = Variable()
    A = Parameter(name='A', value=300)
    sig = Parameter(name='sig', value=sig)
    x0 = Parameter(name='x0', value=x0)

    model = A*exp(-((x - x0)**2/(2 * sig**2)))
    return model
```

Then I'm going to make some models and fit all my datasets:
```python
m1 = model_maker(x0=15, sig=1.5)
f1 = Fit(m1, xdata1, ydata1)
r1 = f1.execute()

m2 = model_maker(x0=500, sig=50)
f2 = Fit(m2, xdata2, ydata2)
r2 = f2.execute()

print(r1)
print(r2)
```

This all works more or less fine (considering #120), I get the desired. However, what I actually tried before is making all models and fit objects and then doing the fitting:

```python
m1 = model_maker(x0=15, sig=1.5)
m2 = model_maker(x0=500, sig=50)

f1 = Fit(m1, xdata1, ydata1)
f2 = Fit(m2, xdata2, ydata2)

r1 = f1.execute()
r2 = f2.execute()

print(r1)
print(r2)
```

In this case fit1 fails. Why is this the case? Arent the models strong, independent models? 
I suspect its related to `inspect` to get variable names? See also #60. 

I'd say throw out this this `inspect` feature, it keeps causing trouble for me. :)

**Comment by pckroon** [comment]
Try `x = Variable('x')` instead of `x = Variable()`. That way we can be sure where the issue lies. It's also the only thing I can come up with...

Also, I'm definitely in favor of deprecating the `inpect` "feature".

**Comment by tBuLi** [comment]
Although I agree with the sentiment, I do not think `inspect` is to blame here. 

This is simply a result of how `sympy` works: there can only be one variable with a given name. `sympy` tracks this globally. So upon making `m2`, `m1`'s variables are overwritten by the new ones, and will therefore have the wrong guesses. 

I agree that this seems very arbitrary, but the only solution is to enforce different variable names.

**Comment by pckroon** [comment]
Long live commenting at the same time. 

That is the most annoying sympy "feature" I've yet seen. I guess it's to reduce the memory footprint, but who hasn't got 16GB RAM nowadays??
But back to the problem: you can keep track of how often you have made a model using that function using a global variable (or make a class and use an instance variable), and use that to change the variables' and parameters' names. It's not pretty, but I think it should work.

**Comment by tBuLi** [comment]
Then just make `model_maker` into a class, it already sounds like one. By overloading `__call__` you could even make it behave identically to a function from the viewpoint of existing code.

I am not sure why they do this in `sympy`, but I'm sure they have their reasons.  If you don't care about the names, you could also opt to go for Dummy variables: `Dummy('x')`. These are going to be trully unique, e.g. `Dummy("x") == Dummy("x")` gives false.

You can use this in place of a sympy Variable out of the box because those do not _currently_ do anything more than standard sympy symbols, and for Parameters I think you could define a new class: `DummyParameter(Dummy, Parameter): pass` and keep your fingers crossed.

That might actually be something worth looking in to because I can imagine that in advanced usecases this bug could appear quite easily.

I'm actually now thinking if my own ALEX Suite doesn't have this problem. Don't tell the boss... ;)

**Comment by Jhsmit** [comment]
haha yes it does sound like some of the more obscure errors in ALEX Suite might be related to this... luckily not just anybody can view these comments :)

**Comment by pckroon** [comment]
From sympy's point of view it might actually make sense, because `Variable('x') + Variable('x')` had better be `2*x`, instead of `x+x`. The reduced memory footprint is a nice bonus.
@tBuLi: Shouldn't it be `class DummyParameter(Parameter, Dummy): pass`?

**Comment by Jhsmit** [comment]
``class DummyParameter(Dummy, Parameter): pass``

Will give you a 
``TypeError: multiple bases have instance lay-out conflict``
