### ISSUE TITLE
Setting a negative fixed parameter

### ISSUE THREAD

**Issue by tex-downey** [tBuLi/symfit#131]
I am needing to set a negative fixed parameter for a model. This may be an issue or user error. I started the following stack exchange question. 

https://stackoverflow.com/questions/44562190/setting-a-negative-fixed-parameter-in-the-symfit-python-package

Sorry for leaving a comment on Git, but both Stack Exchange and Git removed the ability to send comments so I figured this would be the best way to alert those who work on the project as Stack Exchange does not have a Symfit tag.

**Comment by tBuLi** [comment]
Hey @tex-downey, thanks for reporting this. I think you are right, it seems to be an issue, I am looking into it now.

There seem to be 2 problems here:
- I never thought about negative values when building this. Stupid mistake.
- SLSQP does not seem like a good choice when there are no constraints. That should be changed. As a quick fix to your problem, use `NumericalLeastSquares` instead of `Fit`.

I will have a patch for this shortly.

p.s. I am working on that symfit tag, I am close to a 1000 reputation on there and then I should be able to start an official tag ;). I will therefore also answer you on stackoverflow if you don't mind :).
