### ISSUE TITLE
Likelihood NaN

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#21]
Likelihood fitting does not always work, it quite easely results in NaN. This can be caused by giving poor initial conditions, but also has more fundamental reasons. In particular I would preffer to use likelihood rather than loglikelihood because likelihood is always a number between 0 and 1, whereas loglikelihood can be between -inf and 0, which might be problematic.

Currently, the following is minimised:
`ans = - np.nansum(np.log(func(x, p)))`
Thereby maximizing the loglikelihood. I would prefer to minimize the following:
`ans = - np.product(func(x, p))`
However, this does not work nearly as good. How come?

**Comment by mobiusklein** [comment]
Without knowing more about "not nearly as good", the only suggestion that comes to mind is [arithmetic underflow](http://en.wikipedia.org/wiki/Arithmetic_underflow), which results in a loss of precision. Underflow is especially bad when multiplying decimals with large non-whole-number components, which is common for probabilities.

By using log-scale values, we can use addition instead of multiplication, which is less prone to underflow errors, while being able to get back the normal scale value at the end. No matter what, we're losing precision due to using IEEE floating point value representation, but using log scale values keeps this to a minimum.

Great library idea. I was happy to have stumbled across it.

**Comment by tBuLi** [comment]
Thanks for your reply. 

I was afraid that since probabilities between 0 and 1 are transformed to values between -inf and 0, problems might occur if you have to add a couple of monster negative values, whereas when multiplying numbers between 0 and 1 you at least are confined to that range. Off-course those get very small very fast, and my knowledge of the float definition is not good enough to know which is worse. But your argument makes sense, we'll stick with log scale then.

I'm glad you like this project! Because my studies require a lot of time I am not always able to roll out new features and ideas as quickly as I would like, so any feedback or contribution is much appreciated ;). I'll also start working on some API-docs soon to make contributing easier.

**Comment by mobiusklein** [comment]
The only alternative to using log-scale values is to use "multiple precision"  numeric types which are structures that represent real number values as a combination of values as opposed to a single primitive type. Because they aren't represented at the hardware level the way primitive types like integers, and doubles (the underlying C type used to represent Python floats), they require substantially more work to operate on.

```python
x = 0.00000021210001 + 0.00000221212413

x - 0.00000221212413
# 2.1210000999999988e-07, not exactly what we started with

# In [22]: %timeit x - 0.00000221212413
# 10000000 loops, best of 3: 123 ns per loop

import decimal
xd = decimal.Decimal("0.00000021210001") + decimal.Decimal("0.00000221212413")

xd - decimal.Decimal("0.00000221212413")
# Decimal('2.1210001E-7'), exactly what we started with

# In [24]: %timeit xd - decimal.Decimal("0.00000221212413")
# 10000 loops, best of 3: 66 µs per loop
```
In addition to the performance hit of several orders of magnitude, the Decimal type doesn't play well with numpy or the Python floats, and this multiple precision numeric type doesn't have an analog when it is copied into C/Fortran-space where most of numpy and scipy do most of their high performance numerical operations.
