### ISSUE TITLE
import symfit vs symfit.api

### ISSUE THREAD

**Issue by tBuLi** [tBuLi/symfit#29]
For increased readability of code, I think ```symfit.api``` should be replaced by just ```symfit```. The ```.api``` syntax was taken from several other projects I had been working in and where it seemed to make sense. (Traits, enaml)

However, in python we don't typically do this so it feels wrong to me now.

Importing from .api should give a deprication warning.

**Comment by Eljee** [comment]
When working on a set of documentation to contribute at some point, I found that the `symfit.api` structure is not very clear when 'browsing' through the docs. Is there any indication when this will be changed? Is there a plan to create milestone to show future plans?

**Comment by tBuLi** [comment]
Unclear how? Does sphynx autodoc have problems indexing because of this? Or do you mean to read?

Issue #30 has priority at the moment, and then I'll get to this and some other minor issues. In implementing #30 I found that large parts of the internal API have to be rewritten in order to maintain backwards compatibility, which basically means supporting positional arguments. The internal API will also greatly benefit from this revision, but unfortunately this means the fix is taking more time than anticipated. 

Depending on the nature of your problem, I could kick this one to the top of the queue though?

On the point of milestones, I'll see what I can do about that. Creating milestones would make contributing easier so I'm all for it. However, writing clear milestones takes time, which... You get the picture ;).

**Comment by Eljee** [comment]
Probably I should have led with what is unclear. 
It might well be that the unclear documentation is largely due to the fact I'm not used to looking at documentation nested within an API. Reguarding Sphinx: as far as I can auto-generate some docs, there is no way to circumvent the fact that most of the documentation generated is from the `symfit` module within the `symfit` package, this leads to a cluttered TOC-Tree and a less easy to oversee documentation in my opinion. 

With respect to Issue #30, I would say that if the internal API is changed/benefited from this revision, I think it is very wise to first finish this, as the documentation then needs to change accordingly.

**Comment by tBuLi** [comment]
Importing directly from ``symfit`` is now allowed, so I'm closing this issue. I think I also changed this in the docs everywhere, but if not any help tracking these errors would be appreciated.
