### ISSUE TITLE
Symfit.version is missing

### ISSUE THREAD

**Issue by pckroon** [tBuLi/symfit#35]
Currently it is impossible to easily check programmatically what version of symfit is installed, since there is no symfit.version or any equivalent.

**Comment by jbarnoud** [comment]
The convention is to have `symfit.__version__`. It is especially convenient to write bug report.

**Comment by tBuLi** [comment]
Currently this is not that easy, because the versions are automatically determined by[ `pbr` ](https://docs.openstack.org/pbr/3.1.1/#version)when a commit is tagged. 

A posible solution is to use `pbr` to generate `symfit.__version__` as is done [here](https://stackoverflow.com/questions/40562270/how-to-load-package-version-into-version-variable-if-you-are-using-pbr), but that introduces `pbr` as a dependency to `symfit`, which I think is weird since it is a packaging tool which has nothing to do with fitting.

**Comment by jbarnoud** [comment]
With @pckroon we choose to depend on `pbr` for one of our libraries. An other option is to have `setup.py` overwrite a `version.py` module. I did something similar for the for the `authors` variable of MDAnalysis this we generate from an `AUTHORS` file.: https://github.com/MDAnalysis/mdanalysis/blob/1a1b2f1442d52d1216b53b32c4c42c3b47368d38/package/setup.py#L401

**Comment by pckroon** [comment]
And, option 3, maybe we can pull it from `pkg_resources.get_distribution('symfit').version`. Although that might secretly come from pbr.

**Comment by tBuLi** [comment]
Yes indeed, but it wouldn't introduce it as a dependency because it was already generated upon setup, so that way we use the same one `pip` uses. That is probably the best idea actually, although it will return the version of symfit you have installed, not that from the current directory. So i'm not sure this will work for our travis-ci build, does that run setup.py explicitly actually?

**Comment by pckroon** [comment]
Travis does `pip install`, which to my knowledge does `python setup.py install`

**Comment by tBuLi** [comment]
Alright, a PR has been created. Could you review it to see if you agree?
https://github.com/tBuLi/symfit/pull/167
