### ISSUE TITLE
Trivial error in README.md

### ISSUE THREAD

**Issue by zunzun** [tBuLi/symfit#71]
The first example at the top of README.md has the line of code

fit = Fit(model, x=xdata, y=ydata, sigma_y=sigma)

It looks like the variable sigma in "sigma_y=sigma" is undefined in this example.

**Comment by tBuLi** [comment]
Thanks for your comment :). 

Yes, it is undefined (as are `xdata` and `ydata`). I did that deliberately because importing data is always ugly to look at so I don't want that to distract from the clean look of the rest of the code. It's more of a sketch of how clean the fitting code is, rather than a working example.

But if you have any suggestions on how to make it into a fully functional minimal example without making the code appear cluttered I will definitely include it.

**Comment by zunzun** [comment]
Three lines of code defining a minimal working set should look OK, something like this:

xdata = [1.0, 2.0, 3.0, 4.0, 5.0]
xdata = [2.2, 3.3, 4.4, 5.5, 6.6]
sigma = [1.0, 1.0, 1.0, 1.0, 1.0]

It would then run by copy-and-paste for Ye Coding Newbie.

If you would be so kind, I would like to discuss the history and fitting philosophy behind my Python curve fitting code, particularly with respect to both my use of a genetic algorithm to generate initial coefficients and the creation of GUI and web example applications.  For my fitting library pyeq3, I have made both as shown on GitHub here:

https://github.com/zunzun/pyeq3/tree/master/Examples

If you have time later, please email me directly.

James Phillips, zunzun@zunzun.com

**Comment by tBuLi** [comment]
Yeah you're right actually, adding those lines won't impact readability. I'll change it.

FYI, `sigma` is a measurement error by default in `symfit`, not a relative error. So I'll change your sigma array to 0.1's. For more on why I believe this to be the correct, I have a case study in the docs here: http://symfit.readthedocs.io/en/latest/sigma.html. I actually think `scipy` should stress a lot more that it does not interpret sigma as a measurement error by default, because a lot of people might just end up citing the wrong uncertainties in their fit parameters.

I quickly browsed through your project already and was intrigued as to what it was, so I'll definitely send you an email.

**Comment by zunzun** [comment]
Cool.  I look forward to both your email and discussion with another author of a different open source Python fitting library.
